sudo: false
language: python
python:
- '2.7'
- '3.6'
before_script:
- pip install -e .
- pip install pycodestyle
- pip install coverage
- pip install python-coveralls
- cp travis-ci/manage.py manage.py
script:
- pycodestyle --exclude=aws_message/tests aws_message
- python -m compileall aws_message/
- coverage run --source=aws_message/ manage.py test aws_message
after_success:
- coveralls
before_deploy:
- find aws_message/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > aws_message/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: aw7fhEmszj2LkHgX1VZbvXrw1gJWpn1UEu2gn6eaduElY6waIlQ4dk0dl+t6UdSEGKtfDQ9ZwrdSClFWpEti52xwEM0ATQQXGskdbR1GGy2HP29ns14rMhlwb4CfZXoLOeHIA55P6HxMqPC9hg6FtkJAvXhZZe6/Y3MWXjSqOX2skhBHWwoj93b0ZrOfgtw7+8BzexxMXSdIjO8Vs3runFtHWmkBVp1CaHRypBaNRq3v5jXpW4Vh4z1M8A3zb1JF439PKYbURJXN62LOf//Zf0eBRt5/mYnsWl3gLXbq9t48IaF61TDL61wEsPFDcGlUfIu7ucVBYUaQ16KAUMlGfEjRVY5THWZ0Oz+tLvJ3yk7w9zWEa6Ow4FHzR8EF7W6fVsTD4sUffsw3P1XHxGQxyp54JrLATiTfDHzRlEEFHlToV/bPvZFPiN6gessvD+XS67ipRnQTNgSBJ/o1Unhf3esfIlE1GYj4434Oi6m29LdZqZ7/H57+HVKvH0p2zzHsVtcuW/TgoLAYlzg9HdmctNVmqs0o2Hb0DgPCxeJ4/SdEdpwHtRz1ZnGUIWaKs58BWCvH06ROBG/5Isr3gufDXZoPAGKP0JkWkzzI1tFxDtEzpqTnu0/hgRZilzECA6r5DcOHNmjB/4is5O/HdjhKImKeIw5pyx+ZEK3Za+xFBj4=
  on:
    tags: true
    python: '3.6'
